apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: site-benjamin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/site-benjamin.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
